name: Selenium IDE CLI .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test Project 1
      env:
        CHROMEWEBDRIVER: /usr/bin
      run: dotnet test TestProject1 --configuration Release --no-build --verbosity normal
      
    - name: Test Project 2
      env:
        CHROMEWEBDRIVER: /usr/bin
      run: dotnet test TestProject2 --configuration Release --no-build --verbosity normal
      
    - name: Test Project 3
      env:
        CHROMEWEBDRIVER: /usr/bin
      run: dotnet test TestProject3 --configuration Release --no-build --verbosity normal
